-- Minimal Bitrix schema for SuperExport integration tests (MySQL)
CREATE TABLE IF NOT EXISTS b_iblock (
    ID INT PRIMARY KEY,
    IBLOCK_TYPE_ID VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS b_iblock_element (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IBLOCK_ID INT,
    NAME VARCHAR(255),
    CODE VARCHAR(255),
    DETAIL_TEXT LONGTEXT,
    PREVIEW_TEXT TEXT,
    ACTIVE CHAR(1) DEFAULT 'Y',
    DATE_CREATE DATETIME,
    TIMESTAMP_X DATETIME,
    IBLOCK_SECTION_ID INT DEFAULT 0,
    SORT INT DEFAULT 500
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS b_iblock_section (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IBLOCK_ID INT,
    NAME VARCHAR(255),
    CODE VARCHAR(255),
    DESCRIPTION TEXT,
    IBLOCK_SECTION_ID INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS b_iblock_property (
    ID INT PRIMARY KEY,
    CODE VARCHAR(50),
    IBLOCK_ID INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS b_iblock_element_property (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IBLOCK_ELEMENT_ID INT,
    IBLOCK_PROPERTY_ID INT,
    VALUE TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO b_iblock (ID, IBLOCK_TYPE_ID) VALUES (1, 'news');
INSERT INTO b_iblock_section (IBLOCK_ID, NAME, CODE, DESCRIPTION) VALUES (1, 'Bitrix Cat', 'bitrix-cat', 'Section');
INSERT INTO b_iblock_element (IBLOCK_ID, NAME, CODE, DETAIL_TEXT, PREVIEW_TEXT, ACTIVE, DATE_CREATE, TIMESTAMP_X, IBLOCK_SECTION_ID)
VALUES (1, 'Bitrix Post', 'bitrix-post', '<p>From Bitrix</p>', 'Excerpt', 'Y', NOW(), NOW(), 1);
